# Generated by Django 5.2.14 on 2026-05-20 14:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(choices=[('fin', 'Financeiro'), ('jur', 'Jurídico'), ('ma', 'Marketing'), ('rh', 'Recursos Humanos'), ('ti', 'Tecnologia da Informação'), ('ou', 'Outros')], max_length=3)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('motivo_reabertura', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('pergunta', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('reaberta_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('respondida', 'Respondida')], default='aberta', max_length=20)),
                ('titulo', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to=settings.AUTH_USER_MODEL)),
                ('reaberta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resposta', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to=settings.AUTH_USER_MODEL)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.pergunta')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
